version: "3.5"

services:
  mysql:
    build: ./mysql
    ports:
      - target: 3306
        published: 3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
      - SET_CONTAINER_TIMEZONE=true
      - CONTAINER_TIMEZONE=Asia/Shanghai
    networks:
      - my-net

  backend:
    build: ./backend
    ports:
      - target: 3000
        published: 3000
    restart: on-failure
    networks:
      - my-net
    volumes:
      - backend-vol:/usr/local/code
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - target: 8080
        published: 8080
    restart: on-failure
    networks:
      - my-net
    volumes:
      - frontend-vol:/usr/local/code
    depends_on:
      - mysql
      - backend

networks:
  my-net:

volumes:
  frontend-vol:
  backend-vol: